export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGIN_IS_LOADING = 'ADMIN_LOGIN_IS_LOADING';
export const ADMIN_LOGIN_IS_SUCCESS = 'ADMIN_LOGIN_IS_SUCCESS';
export const ADMIN_LOGIN_IS_ERROR = 'ADMIN_LOGIN_IS_ERROR';
