export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_IS_ERROR = 'GET_USER_DETAILS_IS_ERROR';
export const GET_USER_DETAILS_IS_SUCCESS = 'GET_USER_DETAILS_IS_SUCCESS';
export const GET_USER_DETAILS_IS_LOADING = 'GET_USER_DETAILS_IS_LOADING';
