export const PROVIDER_REGISTER = 'PROVIDER_REGISTER';
export const PROVIDER_REGISTER_LOADING_TOGGLE = 'PROVIDER_REGISTER_LOADING_TOGGLE';
export const PROVIDER_REGISTER_IS_SUCCESS = 'PROVIDER_REGISTER_IS_SUCCESS';
export const PROVIDER_REGISTER_IS_FAILURE = 'PROVIDER_REGISTER_IS_FAILURE';

export const PROVIDER_LOGIN = 'PROVIDER_LOGIN';
export const PROVIDER_LOGIN_LOADING_TOGGLE = 'PROVIDER_LOGIN_LOADING_TOGGLE';
export const PROVIDER_LOGIN_IS_SUCCESS = 'PROVIDER_LOGIN_IS_SUCCESS';
export const PROVIDER_LOGIN_IS_FAILURE = 'PROVIDER_LOGIN_IS_FAILURE';
export const PROVIDER_UPDATE_SERVICE="PROVIDER_UPDATE_SERVICE";
export const PROVIDER_UPDATE_EXPERTISE="PROVIDER_UPDATE_EXPERTISE";
export const PROVIDER_UPDATE_IS_ERROR="PROVIDER_UPDATE_IS_ERROR";
export const PROVIDER_UPDATE_IS_LOADING="PROVIDER_UPDATE_IS_LOADING"
export const PROVIDER_UPDATE_IS_SUCCESS="PROVIDER_UPDATE_IS_SUCCESS";



export const PROVIDER_APPROVAL = 'PROVIDER_APPROVAL';
export const PROVIDER_APPROVAL_IS_LOADING = 'PROVIDER_APPROVAL_IS_LOADING';
export const PROVIDER_APPROVAL_IS_SUCCESS = 'PROVIDER_APPROVAL_IS_SUCCESS';
export const PROVIDER_APPROVAL_IS_FAILURE = 'PROVIDER_APPROVAL_IS_FAILURE';

export const GET_UNAPPROVED_PROVIDER = 'GET_UNAPPROVED_PROVIDER';
export const GET_UNAPPROVED_PROVIDER_IS_LOADING = 'GET_UNAPPROVED_PROVIDER_IS_LOADING';
export const GET_UNAPPROVED_PROVIDER_IS_SUCCESS = 'GET_UNAPPROVED_PROVIDER_IS_SUCCESS';
export const GET_UNAPPROVED_PROVIDER_IS_FAILURE = 'GET_UNAPPROVED_PROVIDER_IS_FAILURE';

export const GET_ALL_APPROVED_PROVIDER = 'GET_ALL_APPROVED_PROVIDER';
export const GET_ALL_APPROVED_PROVIDER_IS_LOADING = 'GET_ALL_APPROVED_PROVIDER_IS_LOADING';
export const GET_ALL_APPROVED_PROVIDER_IS_SUCCESS = 'GET_ALL_APPROVED_PROVIDER_IS_LOADING_IS_SUCCESS';
export const GET_ALL_APPROVED_PROVIDER_IS_FAILURE = 'GET_ALL_APPROVED_PROVIDER_IS_LOADING_IS_FAILURE';

export const GET_PROVIDER_BY_ID = 'GET_PROVIDER_BY_ID';
export const GET_PROVIDER_BY_ID_IS_LOADING = 'GET_PROVIDER_BY_ID_IS_LOADING';
export const GET_PROVIDER_BY_ID_IS_SUCCESS = 'GET_PROVIDER_BY_ID_IS_SUCCESS';
export const GET_PROVIDER_BY_ID_IS_FAILURE = 'GET_PROVIDER_BY_ID_IS_FAILURE';

export const GET_ALL_PROVIDERS = 'GET_ALL_PROVIDERS';
export const GET_ALL_PROVIDERS_IS_LOADING = 'GET_ALL_PROVIDERS_IS_LOADING';
export const GET_ALL_PROVIDERS_IS_SUCCESS = 'GET_ALL_PROVIDERS_IS_LOADING_IS_SUCCESS';
export const GET_ALL_PROVIDERS_IS_FAILURE = 'GET_ALL_PROVIDERS_IS_LOADING_IS_FAILURE';