export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const SEARCH_BY_NAME_IS_LOADING = 'SEARCH_BY_NAME_IS_LOADING';
export const SEARCH_BY_NAME_IS_SUCCESS = 'SEARCH_BY_NAME_IS_SUCCESS';
export const SEARCH_BY_NAME_IS_FAILURE = 'SEARCH_BY_NAME_IS_FAILURE';
export const SEARCH_BY_ID_IS_SUCCESS = 'SEARCH_BY_ID_IS_SUCCESS';
export const SEARCH_BY_ID_IS_FAILURE = 'SEARCH_BY_ID_IS_FAILURE';
