/**
 * @description User spcific action types
 */
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_IS_LOADING = 'USER_UPDATE_IS_LOADING';
export const USER_UPDATE_IS_SUCCESS = 'USER_UPDATE_IS_SUCCESS';
export const USER_UPDATE_IS_ERROR = 'USER_UPDATE_IS_ERROR';

export const USER_FORGOT_PASSWORD = 'USER_FORGOT_PASSWORD';
export const USER_FORGOT_PASSWORD_IS_LOADING = 'USER_FORGOT_PASSWORD_IS_LOADING';
export const USER_FORGOT_PASSWORD_IS_SUCCESS = 'USER_FORGOT_PASSWORD_IS_SUCCESS';
export const USER_FORGOT_PASSWORD_IS_FAILURE = 'USER_FORGOT_PASSWORD_IS_FAILURE';

export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';
export const USER_RESET_PASSWORD_IS_LOADING = 'USER_RESET_PASSWORD_IS_LOADING';
export const USER_RESET_PASSWORD_IS_SUCCESS = 'USER_RESET_PASSWORD_IS_SUCCESS';
export const USER_RESET_PASSWORD_IS_FAILURE = 'USER_RESET_PASSWORD_IS_FAILURE';

