export const GET_COUNTRIES_LIST = 'GET_COUNTRIES_LIST';
export const GET_COUNTRIES_LOADING_TOGGLE = 'LOADING_TOGGLE';
export const GET_COUNTRIES_NETWORK_ACCESS_SUCCESS = 'NETWORK_ACCESS_SUCCESS';
export const GET_COUNTRIES_NETWORK_ACCESS_FAILURE = 'NETWORK_ACCESS_FAILURE';

export const GET_FINANCIAL_SERVICE = 'GET_FINANCIAL_SERVICE';
export const GET_FINANCIAL_SERVICE_LOADING_TOGGLE = 'GET_FINANCIAL_SERVICE_LOADING_TOGGLE';
export const GET_FINANCIAL_SERVICE_NETWORK_ACCESS_SUCCESS = 'GET_FINANCIAL_SERVICE_NETWORK_ACCESS_SUCCESS';
export const GET_FINANCIAL_SERVICE_NETWORK_ACCESS_FAILURE = 'GET_FINANCIAL_SERVICE_NETWORK_ACCESS_FAILURE';

export const GET_BUSINESS_TYPE = 'GET_BUSINESS_TYPE';
export const GET_BUSINESS_TYPE_SERVICE_LOADING_TOGGLE = 'GET_BUSINESS_TYPE_SERVICE_LOADING_TOGGLE';
export const GET_BUSINESS_TYPE_SERVICE_NETWORK_ACCESS_SUCCESS = 'GET_BUSINESS_TYPE_SERVICE_NETWORK_ACCESS_SUCCESS';
export const GET_BUSINESS_TYPE_SERVICE_NETWORK_ACCESS_FAILURE = 'GET_BUSINESS_TYPE_SERVICE_NETWORK_ACCESS_FAILURE';

export const TOGGLE_LOGIN_DIALOG = 'TOGGLE_LOGIN_DIALOG';

export const FILTER_PROVIDER_BY_COUNTRY = 'FILTER_PROVIDER_BY_COUNTRY';
export const FILTER_PROVIDER_BY_SEARCH = 'FILTER_PROVIDER_BY_SEARCH';
export const FILTER_BY_FINANCIAL_SERVICES = 'FILTER_BY_FINANCIAL_SERVICES';
export const FILTER_BY_BUSINESS_SERVICES = 'FILTER_BY_BUSINESS_SERVICES';

export const UPDATE_CITY_LIST = 'UPDATE_CITY_LIST';
export const UPDATE_CITY_LOADING_TOGGLE = 'LOADING_TOGGLE';
export const UPDATE_CITY_NETWORK_ACCESS_SUCCESS = 'NETWORK_ACCESS_SUCCESS';
export const UPDATE_CITY_NETWORK_ACCESS_FAILURE = 'NETWORK_ACCESS_FAILURE';